{"uuid": "b43e2e31-dbe8-4c4d-a86b-81d3f10287f9", "children": ["174c0789-2c67-4b5f-a6db-e7ea3e7f1d0c"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error getting device API level. Original error: Error executing adbExec. Original error: 'Command '/Users/yaroslav.petryk/Library/Android/sdk/platform-tools/adb -P 5037 -s 18241FDF600BJ0 shell getprop ro.build.version.sdk' exited with code 1'; Command output: adb: device unauthorized.\nThis adb server's $ADB_VENDOR_KEYS is not set\nTry 'adb kill-server' if that seems wrong.\nOtherwise check for a confirmation dialog on your device.\n\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Error getting device API level. Original error: Error executing adbExec. Original error: 'Command '/Users/yaroslav.petryk/Library/Android/sdk/platform-tools/adb -P 5037 -s 18241FDF600BJ0 shell getprop ro.build.version.sdk' exited with code 1'; Command output: adb: device unauthorized.\nThis adb server's $ADB_VENDOR_KEYS is not set\nTry 'adb kill-server' if that seems wrong.\nOtherwise check for a confirmation dialog on your device.\n\n    at getResponseForW3CError (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)\n    at asyncHandler (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)\n", "trace": "  File \"/Users/yaroslav.petryk/Desktop/projects/powerfox-app-native-android/tests/venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/yaroslav.petryk/Desktop/projects/powerfox-app-native-android/tests/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/yaroslav.petryk/Desktop/projects/powerfox-app-native-android/tests/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/yaroslav.petryk/Desktop/projects/powerfox-app-native-android/tests/tests/conftest.py\", line 19, in driver\n    appium_driver = webdriver.Remote(url, capabilities)\n  File \"/Users/yaroslav.petryk/Desktop/projects/powerfox-app-native-android/tests/venv/lib/python3.10/site-packages/appium/webdriver/webdriver.py\", line 230, in __init__\n    super().__init__(\n  File \"/Users/yaroslav.petryk/Desktop/projects/powerfox-app-native-android/tests/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 276, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/Users/yaroslav.petryk/Desktop/projects/powerfox-app-native-android/tests/venv/lib/python3.10/site-packages/appium/webdriver/webdriver.py\", line 320, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n  File \"/Users/yaroslav.petryk/Desktop/projects/powerfox-app-native-android/tests/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 434, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/yaroslav.petryk/Desktop/projects/powerfox-app-native-android/tests/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1683573598265, "stop": 1683573613798}], "start": 1683573598265, "stop": 1683573613932}